package tunutech.api.model;

public enum ActivityType {
    // Utilisateurs
    USER_REGISTERED,
    USER_UPDATED,
    USER_DELETED,
    USER_PROFILE_UPDATED,
    USER_ROLE_CHANGED,

    // Projets
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_COMPLETED,
    PROJECT_CANCELLED,
    CONTRACT_GENERATED,
    CONTRACT_ACCEPTED,
    CONTRACT_REFUSED,
    PROJECT_ASSIGNED,
    PROJECT_DELIVERED,

    // Traductions
    TRANSLATION_STARTED,
    TRANSLATION_COMPLETED,
    TRANSLATION_REVIEWED,
    TRANSLATION_DELIVERED,

    // Paiements
    PAYMENT_PROCESSED,
    PAYMENT_FAILED,
    INVOICE_GENERATED,
    PAYMENT_REFUNDED,

    // Système & Admin
    SYSTEM_NOTIFICATION,
    ADMIN_ACTION,
    SETTINGS_UPDATED,
    BACKUP_CREATED
}
